doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

#        # note:utf8mb4 needed for emoticons and extra chars of some languages
#        # only needed for MySQL
#        charset: utf8mb4
#        default_table_options:
#            collate: utf8mb4_unicode_ci

        #previous default value of old symfony releases.
        charset: UTF8
        default_table_options:
            collate: utf8_general_ci #guessed!

        # backtrace queries in profiler (increases memory usage per request)
        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
