framework:
    router:
        utf8: true


when@prod:
    framework:
        router:
            strict_requirements: null
            # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
            # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
            default_uri: https://translate.dokuwiki.org