imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: services.yml }

parameters:



# Assetic Configuration
#assetic:
#    debug:          '%kernel.debug%'
#    use_controller: true
#    #java: '/usr/bin/java'
#    filters:
#        cssrewrite: ~
#       #less:
#        #    node: /usr/bin/node
#        #    node_paths:
#        #        - '%kernel.project_dir%/node_modules'
#        lessphp:
#            file: '%kernel.project_dir%/vendor/leafo/lessphp/lessc.inc.php'
#            apply_to: '\.less$'



gregwar_captcha: ~

## temporary
#sensio_framework_extra:
#    router:
#        annotations: false