imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: services.yml }

parameters:
    container.autowiring.strict_mode: true

framework:
    #esi:             ~
    #translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: '%kernel.debug%'
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session:         ~
    assets: ~

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'dokuwikiTranslatorBundle:Template:fields.html.twig'

# Assetic Configuration
#assetic:
#    debug:          '%kernel.debug%'
#    use_controller: true
#    #java: '/usr/bin/java'
#    filters:
#        cssrewrite: ~
#       #less:
#        #    node: /usr/bin/node
#        #    node_paths:
#        #        - '%kernel.project_dir%/node_modules'
#        lessphp:
#            file: '%kernel.project_dir%/vendor/leafo/lessphp/lessc.inc.php'
#            apply_to: '\.less$'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

gregwar_captcha: ~

## temporary
#sensio_framework_extra:
#    router:
#        annotations: false