
App\Entity\RepositoryEntity:
  properties:
    url:
      - NotBlank: ~
      - Url: { protocols: [http, https, git, ssh] }
    branch:
      - NotBlank: ~
      - Regex: '/^\S+$/'
    email:
      - NotBlank: ~
      - Email: ~
    name:
      - NotBlank: ~
      - Regex: '/^[a-z0-9]+$/'
      - org\dokuwiki\translatorBundle\Validator\PluginName:
          groups: [plugin]
      - org\dokuwiki\translatorBundle\Validator\TemplateName:
          groups: [template]
  constraints:
    - org\dokuwiki\translatorBundle\Validator\CustomUniqueEntity:
        fields: [name, type]
        #            errorPath: name
        message: "There is already a registered {{ type }} with the name \"{{ name }}\"."

