name: PHP Code Style

on:
  push:
    branches-ignore:
      - stable
      - old-stable
  pull_request:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: cs2pr, phpcs

            - name: run PHP codesniffer
              run: phpcs -q --standard=.github/workflows/phpcs.xml --report=checkstyle | cs2pr
